name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Ensure GITHUB_TOKEN has write permissions

jobs:
  build-test:
    name: Build Layer for Pipeline
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build and test the app"

  docker-build-and-push:
    name: Build and Push Image
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU on the server
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ github.run_id }}
  update-deployment-file:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Get Image Tag
        id: tag
        run: echo "tag=${{ github.run_id }}" >> $GITHUB_OUTPUT
    
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set file permissions
        run: chmod 777 deploy/deployment.yml
    
      - name: Update Deployment YAML
        run: |
          sed -i "s|image:.*$|image: obusorezekiel/demo-node-app:${{ github.run_id }}|g" deploy/deployment.yml
          cat deploy/deployment.yml
        env:
          github_token: ${{ secrets.GH_PAT }}    

      - name: Commit changes
        run: |
          git config --global user.email "ci-bot@argocd.com"
          git config --global user.name "ci-bot"
          git add deploy/deployment.yml    
          git commit -m "Update image tag [skip ci]"
        env:
          github_token: ${{ secrets.GH_PAT }}
        
        #Commit
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
            